# Inspiration: https://github.com/edx/configuration/blob/master/.travis.yml
env: 
  global: 
    - IPOPT_DEFAULT_LINEAR_SOLVER=ma57
    - LD_LIBRARY_PATH=/home/travis/build/libhsl
    - secure: KvMG4VORV7Ja09shvmsMpiaRMoWqupR76dKxOd7W28I//F4YDIn5ZZefM4aoXsmRgs4G9YqloU8JjVpHutZARmKn2drUwHVMA+96iKb9eDODwZaKXgFYsrQIX5c/OgO8ZpsXynD2daqH3bMK8Mjz1+4fjbFToPFXHggxqQuHm1U=
    - CMAKE_INCLUDE_PATH=/home/travis/build/testbot/restricted/cplex/cplex/include:/home/travis/build/testbot/restricted/cplex/concert/include
    - CMAKE_LIBRARY_PATH=/home/travis/build/testbot/restricted/cplex/cplex/lib/x86-64_sles10_4.1/static_pic/:/home/travis/build/testbot/restricted/cplex/concert/lib/x86-64_sles10_4.1/static_pic/
    - ILOG_LICENSE_FILE=/home/travis/build/testbot/restricted/cplex/access.ilm
    - WORHP=/home/travis/build/testbot/restricted/worhp
    - WORHP_LICENSE_FILE=/home/travis/build/testbot/restricted/worhp/unlocked.lic
    - SNOPT=/home/travis/build/snopt7
    - MATLABPATH=/home/travis/build/matlab-install
    - MATLAB_ROOT=/home/travis/build/matlab

before_script:
  - set -e

script:
  - mkdir build
  - pushd build
  - |
    cat <<EOF >toolchain.cmake
    # this one is important
    SET(CMAKE_SYSTEM_NAME Windows)
    #this one not so much
    SET(CMAKE_SYSTEM_VERSION 1)
    
    # x86_64
    SET(PREFIX i686-w64-mingw32)
    
    # specify the cross compiler
    SET(CMAKE_C_COMPILER   ${PREFIX}-gcc)
    SET(CMAKE_CXX_COMPILER ${PREFIX}-g++)
    SET(CMAKE_Fortran_COMPILER ${PREFIX}-gfortran)
    set(CMAKE_RC_COMPILER ${PREFIX}-windres)
    
    #SET( CMAKE_CXX_FLAGS  "${CMAKE_CXX_FLAGS} -target=--${PREFIX}" )
    #SET( CMAKE_EXE_LINKER_FLAGS  "${CMAKE_EXE_LINKER_FLAGS} -target=--target=${PREFIX}" )
    # where is the target environment 
    SET(CMAKE_FIND_ROOT_PATH  /usr/${PREFIX})
    
    # search for programs in the build host directories
    SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
    # for libraries and headers in the target directories
    SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
    SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
    EOF
  - cmake -DCMAKE_TOOLCHAIN_FILE=../toolchain.cmake -DWITH_PYTHON=ON ..
  - make -j2
        
branches:
  except:
    - /.*appveyor.*/

before_install:
  - sudo apt-get update
  - DEBIAN_FRONTEND=noninteractive DEBIAN_PRIORITY=critical sudo apt-get -u -q -y -o "Dpkg::Options::=--force-confdef" -o "Dpkg::Options::=--force-confold" dist-upgrade
  - sudo apt-get install mingw-w64
  - pushd ../../ && git clone https://github.com/casadi/testbot.git
  - pushd testbot && recipes/setup.sh && popd
  - sudo apt-get install p7zip-full -y
  - travis_retry testbot/recipes/fetch.sh libhsl.tar.gz && mkdir libhsl && tar -xvf libhsl.tar.gz -C libhsl
  - travis_retry testbot/recipes/fetch.sh snopt7.tar.gz && mkdir snopt7 && tar -xvf snopt7.tar.gz -C snopt7
  - mkdir -p /home/travis/build/casadi/testbot
  - travis_retry testbot/recipes/fetch.sh swig.tar.gz && mkdir swig && tar -xvf swig.tar.gz -C swig
  - pushd /home/travis/build/casadi/testbot && ln -s  /home/travis/build/swig  swig-install  && popd
  - travis_retry testbot/recipes/fetch.sh swig_matlab.tar.gz && mkdir swig_matlab && tar -xvf swig_matlab.tar.gz -C swig_matlab
  - pushd /home/travis/build/casadi/testbot && ln -s  /home/travis/build/swig_matlab  swig-matlab-install  && popd
  - export PATH=/home/travis/build/swig/bin:$PATH
  - pushd testbot/restricted/cplex && mkdir cplex && tar -xvf cplex12.4.tar.gz -C cplex && mkdir concert && tar -xvf cplex12.4-concert.tar.gz -C concert && popd
  - pushd testbot/restricted && mkdir -p worhp && cd  worhp && 7za e ../libworhp_debian7_amd64_gcc47_1.7-12970f3.7z -y && popd
  - popd
  - sudo add-apt-repository ppa:umn-claoit-rce/compute-packages -y
  - sudo add-apt-repository ppa:baltix-members/ppa -y #  for libslicot-dev
  - sudo apt-get update -qq
  - sudo apt-get install -y binutils gcc g++ gfortran git cmake liblapack-dev ipython python-dev python-numpy python-scipy python-matplotlib coinor-libipopt-dev libmumps-seq-dev libblas-dev liblapack-dev libslicot-dev libxml2-dev

language: cpp
